-- +goose Up
CREATE TABLE feeds (
	id UUID PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
    url VARCHAR(255) NOT NULL UNIQUE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE feeds;


-- +goose Up
ALTER TABLE feeds ADD COLUMN last_fetched_at TIMESTAMP DEFAULT NULL;

-- +goose Down
ALTER TABLE feeds DROP COLUMN last_fetched_at;